version: "3.1"
services:
  www:
    build:
      dockerfile: ./www/Dockerfile

    restart: on-failure
    volumes:
      - "./:/var/www/html"
    ports:
      - 8082:80
      - 443:443
  db:
    build:
      dockerfile: ./db/Dockerfile
    env_file:
      - variables.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    env_file:
      - variables.env